[machine01]
machine01-jenkin ansible_host=104.197.103.74 internal_ip=10.128.0.2

[machine02]
machine02-sonarqube ansible_host=34.59.145.174 internal_ip=10.128.0.3

[machine03]
machine03-nexus ansible_host=136.111.8.19 internal_ip=10.128.0.4

[jenkins_nodes]
machine01-jenkin

[sonarqube_nodes]
machine02-sonarqube

[nexus_nodes]
machine03-nexus

[all_nodes:children]
machine01
machine02
machine03
